server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/login-demo?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.pagehelperdemo.**.domain
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  supportMethodsArguments: true
  params: count=countSql
